server:
  port: 9092
  
  
eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
   default-zone: http://localhost:8761/eureka/
 instance: 
  hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodcataloguedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: FOODCATALOGUE_SERVICE
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true